import CronogramaActivity, { createActivity, createNewActivity } from "app/externos/gestiones/Solicitud/Generales/Cronograma/CronogramaActivity"
import CronogramaConvert from "./CronogramaConvert"

type CronogramaDTO = {
    delimitacionUnidadManejo: CronogramaActivity,
	delimitacionAreaProduccionYProteccion: CronogramaActivity,
	tomaInformacionCampoYCenso: CronogramaActivity,
	marcacion: CronogramaActivity,
	procesamientoInformacionCampo: CronogramaActivity,
	elaboracionPlanManejo: CronogramaActivity,
	retiroYDisposicionDeDesechos: CronogramaActivity,
	patrullajes: CronogramaActivity,
	identificacionYMapeoAreasCriticas: CronogramaActivity,
	construccionDeBrechas: CronogramaActivity,
	manejoCombustible: CronogramaActivity,
	identificacionPuntosIncendios: CronogramaActivity,
	patrullajesIncendios: CronogramaActivity,
	capacitacionIncendios: CronogramaActivity,
	adquisicionEquipoIncendios: CronogramaActivity,
	controlIncendios: CronogramaActivity,
	monitoreoIncendios: CronogramaActivity,
	medidasPrevencionPlagas: CronogramaActivity,
	medidasControlPlagas: CronogramaActivity,
	monitoreoPlagas: CronogramaActivity,
	mantenimientoLinderos: CronogramaActivity,
	construccionCaminos: CronogramaActivity,
	construccionAcopio: CronogramaActivity,
	talaDirigida: CronogramaActivity,
	arrastreYTransporte: CronogramaActivity,
	presentacionTrimestral: CronogramaActivity,
	retiroDesechos: CronogramaActivity,
	retiroResiduos: CronogramaActivity,
	cierreCaminosSecundarios: CronogramaActivity,
	tratamientoSilviculturales: CronogramaActivity,
	actividadesRepoblacion: CronogramaActivity,
    retiroDesechos2: CronogramaActivity,
	remocion: CronogramaActivity,
    plantacion: CronogramaActivity,
    resiembra: CronogramaActivity,
	informeFinal: CronogramaActivity
    observaciones: string
}

export const createNew = (): CronogramaDTO => {
    return {
        delimitacionUnidadManejo: createNewActivity("Delimitación de la unidad de manejo ", "delimitacionUnidadManejo"),
        delimitacionAreaProduccionYProteccion: createNewActivity("Delimitación del área de producción y protección", "delimitacionAreaProduccionYProteccion"),
        tomaInformacionCampoYCenso: createNewActivity("Toma de información de campo y censo forestal", "tomaInformacionCampoYCenso"),
        marcacion: createNewActivity("Marcación de árboles semilleros, caminos y bacadillas, corte de lianas, diseño de caminos", "marcacion"),
        procesamientoInformacionCampo: createNewActivity("Procesamiento de la información de campo", "procesamientoInformacionCampo"),
        elaboracionPlanManejo: createNewActivity("Elaboración de plan de manejo", "elaboracionPlanManejo"),
        retiroYDisposicionDeDesechos: createNewActivity("Retiro y disposición de desechos sólidos y líquidos", "retiroYDisposicionDeDesechos"),
        patrullajes: createNewActivity("Patrullajes para prevenir talas ilícitas", "patrullajes"),
        identificacionYMapeoAreasCriticas: createNewActivity("Identificación y mapeo de áreas críticas a incendios forestales", "identificacionYMapeoAreasCriticas"),
        construccionDeBrechas: createNewActivity("Construcción de brechas o rondas perimetrales cortafuego", "construccionDeBrechas"),
        manejoCombustible: createNewActivity("Manejo de combustible y / o silvicultura preventiva", "manejoCombustible"),
        identificacionPuntosIncendios: createNewActivity("Identificación de puntos para monitorear incendios forestales", "identificacionPuntosIncendios"),
        patrullajesIncendios: createNewActivity("Patrullajes de monitoreo terrestre para detectar incendios forestales", "patrullajesIncendios"),
        capacitacionIncendios: createNewActivity("Capacitación del personal en prevención y control de incendios forestales", "capacitacionIncendios"),
        adquisicionEquipoIncendios: createNewActivity("Adquisición de equipo para el control de incendios forestales", "adquisicionEquipoIncendios"),
        controlIncendios: createNewActivity("Control y liquidación de incendios forestales", "controlIncendios"),
        monitoreoIncendios: createNewActivity("Monitoreo y evaluación de incendios forestales", "monitoreoIncendios"),
        medidasPrevencionPlagas: createNewActivity("Medidas para la prevención de plagas y enfermedades", "medidasPrevencionPlagas"),
        medidasControlPlagas: createNewActivity("Medidas para el control de plagas y enfermedades", "medidasControlPlagas"),
        monitoreoPlagas: createNewActivity("Monitoreo de plagas y enfermedades forestales", "monitoreoPlagas"),
        mantenimientoLinderos: createNewActivity("Mantenimiento de linderos", "mantenimientoLinderos"),
        construccionCaminos: createNewActivity("Construcción de caminos", "construccionCaminos"),
        construccionAcopio: createNewActivity("Construcción de sitios de acopio", "construccionAcopio"),
        talaDirigida: createNewActivity("Tala dirigida", "talaDirigida"),
        arrastreYTransporte: createNewActivity("Arrastre y transporte", "arrastreYTransporte"),
        presentacionTrimestral: createNewActivity("Presentación de informe trimestral del uso de notas de envío", "presentacionTrimestral"),
        retiroDesechos: createNewActivity("Retiro y disposición de desechos sólidos y líquidos", "retiroDesechos"),
        retiroResiduos: createNewActivity("Retiro o dispersión de residuos en los sitios de tumba y caminos forestales", "retiroResiduos"),
        cierreCaminosSecundarios: createNewActivity("Cierre de caminos secundarios", "cierreCaminosSecundarios"),
        tratamientoSilviculturales: createNewActivity("Tratamientos y prácticas silviculturales", "tratamientoSilviculturales"),
        actividadesRepoblacion: createNewActivity("Actividades de repoblación forestal", "actividadesRepoblacion"),
        retiroDesechos2: createNewActivity("Retiro y disposición de desechos sólidos y líquidos", "retiroDesechos2"),
        remocion: createNewActivity("Remoción de hojarasca para el establecimiento de regeneración natural", "remocion"),
        plantacion: createNewActivity("Plantación", "plantacion"),
        resiembra: createNewActivity("Resiembra", "resiembra"),
        informeFinal: createNewActivity("Presentación del informe final del uso de notas de envío", "informeFinal"),
        observaciones: ""
    }
}

export const convertAsArrayDTO = (cronograma: CronogramaDTO) : CronogramaConvert => {
    return{
        delimitacionUnidadManejo: convertAsArray(cronograma.delimitacionUnidadManejo),
        delimitacionAreaProduccionYProteccion: convertAsArray(cronograma.delimitacionAreaProduccionYProteccion),
        tomaInformacionCampoYCenso: convertAsArray(cronograma.tomaInformacionCampoYCenso),
        marcacion: convertAsArray(cronograma.marcacion),
        procesamientoInformacionCampo: convertAsArray(cronograma.procesamientoInformacionCampo),
        elaboracionPlanManejo: convertAsArray(cronograma.elaboracionPlanManejo),
        retiroYDisposicionDeDesechos: convertAsArray(cronograma.retiroYDisposicionDeDesechos),
        patrullajes: convertAsArray(cronograma.patrullajes),
        identificacionYMapeoAreasCriticas: convertAsArray(cronograma.identificacionYMapeoAreasCriticas),
        construccionDeBrechas: convertAsArray(cronograma.construccionDeBrechas),
        manejoCombustible: convertAsArray(cronograma.manejoCombustible),
        identificacionPuntosIncendios: convertAsArray(cronograma.identificacionPuntosIncendios),
        patrullajesIncendios: convertAsArray(cronograma.patrullajesIncendios),
        capacitacionIncendios: convertAsArray(cronograma.capacitacionIncendios),
        adquisicionEquipoIncendios: convertAsArray(cronograma.adquisicionEquipoIncendios),
        controlIncendios: convertAsArray(cronograma.controlIncendios),
        monitoreoIncendios: convertAsArray(cronograma.monitoreoIncendios),
        medidasPrevencionPlagas: convertAsArray(cronograma.medidasPrevencionPlagas),
        medidasControlPlagas: convertAsArray(cronograma.medidasControlPlagas),
        monitoreoPlagas: convertAsArray(cronograma.monitoreoPlagas),
        mantenimientoLinderos: convertAsArray(cronograma.mantenimientoLinderos),
        construccionCaminos: convertAsArray(cronograma.construccionCaminos),
        construccionAcopio: convertAsArray(cronograma.construccionAcopio),
        talaDirigida: convertAsArray(cronograma.talaDirigida),
        arrastreYTransporte: convertAsArray(cronograma.arrastreYTransporte),
        presentacionTrimestral: convertAsArray(cronograma.presentacionTrimestral),
        retiroDesechos: convertAsArray(cronograma.retiroDesechos),
        retiroResiduos: convertAsArray(cronograma.retiroResiduos),
        cierreCaminosSecundarios: convertAsArray(cronograma.cierreCaminosSecundarios),
        tratamientoSilviculturales: convertAsArray(cronograma.tratamientoSilviculturales),
        actividadesRepoblacion: convertAsArray(cronograma.actividadesRepoblacion),
        retiroDesechos2: convertAsArray(cronograma.retiroDesechos2),
        remocion: convertAsArray(cronograma.remocion),
        plantacion: convertAsArray(cronograma.plantacion),
        resiembra: convertAsArray(cronograma.resiembra),
        informeFinal: convertAsArray(cronograma.informeFinal),
        observaciones: cronograma.observaciones
    };
}

const convertAsArray = (cronogramaActivity: CronogramaActivity) : boolean[] => {
    return [cronogramaActivity.ene, cronogramaActivity.feb, cronogramaActivity.mar, cronogramaActivity.abr,
            cronogramaActivity.may, cronogramaActivity.jun, cronogramaActivity.jul, cronogramaActivity.ago,
            cronogramaActivity.sep, cronogramaActivity.oct, cronogramaActivity.nov, cronogramaActivity.dic];
}

export const convertAsCronogramaDTO = (cronograma: CronogramaConvert) : CronogramaDTO => {
    return{
        delimitacionUnidadManejo: createActivity("Delimitación de la unidad de manejo ", "delimitacionUnidadManejo", cronograma.delimitacionUnidadManejo),
        delimitacionAreaProduccionYProteccion: createActivity("Delimitación del área de producción y protección", "delimitacionAreaProduccionYProteccion", cronograma.delimitacionAreaProduccionYProteccion),
        tomaInformacionCampoYCenso: createActivity("Toma de información de campo y censo forestal", "tomaInformacionCampoYCenso", cronograma.tomaInformacionCampoYCenso),
        marcacion: createActivity("Marcación de árboles semilleros, caminos y bacadillas, corte de lianas, diseño de caminos", "marcacion", cronograma.marcacion),
        procesamientoInformacionCampo: createActivity("Procesamiento de la información de campo", "procesamientoInformacionCampo", cronograma.procesamientoInformacionCampo),
        elaboracionPlanManejo: createActivity("Elaboración de plan de manejo", "elaboracionPlanManejo", cronograma.elaboracionPlanManejo),
        retiroYDisposicionDeDesechos: createActivity("Retiro y disposición de desechos sólidos y líquidos", "retiroYDisposicionDeDesechos", cronograma.retiroYDisposicionDeDesechos),
        patrullajes: createActivity("Patrullajes para prevenir talas ilícitas", "patrullajes", cronograma.patrullajes),
        identificacionYMapeoAreasCriticas: createActivity("Identificación y mapeo de áreas críticas a incendios forestales", "identificacionYMapeoAreasCriticas", cronograma.identificacionYMapeoAreasCriticas),
        construccionDeBrechas: createActivity("Construcción de brechas o rondas perimetrales cortafuego", "construccionDeBrechas", cronograma.construccionDeBrechas),
        manejoCombustible: createActivity("Manejo de combustible y / o silvicultura preventiva", "manejoCombustible", cronograma.manejoCombustible),
        identificacionPuntosIncendios: createActivity("Identificación de puntos para monitorear incendios forestales", "identificacionPuntosIncendios", cronograma.identificacionPuntosIncendios),
        patrullajesIncendios: createActivity("Patrullajes de monitoreo terrestre para detectar incendios forestales", "patrullajesIncendios", cronograma.patrullajesIncendios),
        capacitacionIncendios: createActivity("Capacitación del personal en prevención y control de incendios forestales", "capacitacionIncendios", cronograma.capacitacionIncendios),
        adquisicionEquipoIncendios: createActivity("Adquisición de equipo para el control de incendios forestales", "adquisicionEquipoIncendios", cronograma.adquisicionEquipoIncendios),
        controlIncendios: createActivity("Control y liquidación de incendios forestales", "controlIncendios", cronograma.controlIncendios),
        monitoreoIncendios: createActivity("Monitoreo y evaluación de incendios forestales", "monitoreoIncendios", cronograma.monitoreoIncendios),
        medidasPrevencionPlagas: createActivity("Medidas para la prevención de plagas y enfermedades", "medidasPrevencionPlagas", cronograma.medidasPrevencionPlagas),
        medidasControlPlagas: createActivity("Medidas para el control de plagas y enfermedades", "medidasControlPlagas", cronograma.medidasControlPlagas),
        monitoreoPlagas: createActivity("Monitoreo de plagas y enfermedades forestales", "monitoreoPlagas", cronograma.monitoreoPlagas),
        mantenimientoLinderos: createActivity("Mantenimiento de linderos", "mantenimientoLinderos", cronograma.mantenimientoLinderos),
        construccionCaminos: createActivity("Construcción de caminos", "construccionCaminos", cronograma.construccionCaminos),
        construccionAcopio: createActivity("Construcción de sitios de acopio", "construccionAcopio", cronograma.construccionAcopio),
        talaDirigida: createActivity("Tala dirigida", "talaDirigida", cronograma.talaDirigida),
        arrastreYTransporte: createActivity("Arrastre y transporte", "arrastreYTransporte", cronograma.arrastreYTransporte),
        presentacionTrimestral: createActivity("Presentación de informe trimestral del uso de notas de envío", "presentacionTrimestral", cronograma.presentacionTrimestral),
        retiroDesechos: createActivity("Retiro y disposición de desechos sólidos y líquidos", "retiroDesechos", cronograma.retiroDesechos),
        retiroResiduos: createActivity("Retiro o dispersión de residuos en los sitios de tumba y caminos forestales", "retiroResiduos", cronograma.retiroResiduos),
        cierreCaminosSecundarios: createActivity("Cierre de caminos secundarios", "cierreCaminosSecundarios", cronograma.cierreCaminosSecundarios),
        tratamientoSilviculturales: createActivity("Tratamientos y prácticas silviculturales", "tratamientoSilviculturales", cronograma.tratamientoSilviculturales),
        actividadesRepoblacion: createActivity("Actividades de repoblación forestal", "actividadesRepoblacion", cronograma.actividadesRepoblacion),
        retiroDesechos2: createActivity("Retiro y disposición de desechos sólidos y líquidos", "retiroDesechos2", cronograma.retiroDesechos2),
        remocion: createActivity("Remoción de hojarasca para el establecimiento de regeneración natural", "remocion",  cronograma.remocion),
        plantacion: createActivity("Plantación", "plantacion", cronograma.plantacion),
        resiembra: createActivity("Resiembra", "resiembra",  cronograma.resiembra),
        informeFinal: createActivity("Presentación del informe final del uso de notas de envío", "informeFinal", cronograma.informeFinal),
        observaciones: cronograma.observaciones
    }
}

export default CronogramaDTO